package interfaz;

import drones.*;
import javax.swing.JOptionPane;
import usuarios.*;

public class VentanaAdmin extends javax.swing.JFrame {

    private SistemaGestionDrones sistema;
    private Usuario usuarioLogueado;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAdmin.class.getName());

    public VentanaAdmin(SistemaGestionDrones sistema, Usuario usuarioLogueado) {
        this.sistema = sistema;
        this.usuarioLogueado = usuarioLogueado;
        initComponents();
        llenarComboBoxUsuarios();
        llenarComboBoxEliminar();

    }

    public VentanaAdmin() {

        initComponents();
    }

    private void llenarComboBoxUsuarios() {
        cmbUsuarios.removeAllItems();
        Usuario[] lista = sistema.getUsuarios();
        int total = sistema.getContUsuarios();
        for (int i = 0; i < total; i++) {
            if (lista[i] != null) {
                cmbUsuarios.addItem(lista[i].getUsername());
            }

        }
    }

    private void llenarComboBoxEliminar() {
        cmbUsuarios1.removeAllItems();
        Usuario[] lista = sistema.getUsuarios();
        int total = sistema.getContUsuarios();
        for (int i = 0; i < total; i++) {
            if (lista[i] != null) {
                cmbUsuarios1.addItem(lista[i].getUsername());
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        txtDNI = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmbUsuarios = new javax.swing.JComboBox<>();
        cmbModificar = new javax.swing.JComboBox<>();
        lblNuevoDato = new javax.swing.JLabel();
        txtModificar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        lblActual = new javax.swing.JLabel();
        lblDato = new javax.swing.JLabel();
        lblConsejo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmbUsuarios1 = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración de Usuarios");

        jLabel1.setText("DNI");

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Usuario");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Rol");

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Operador", "Supervisor" }));
        cmbRol.addActionListener(this::cmbRolActionPerformed);

        txtDNI.addActionListener(this::txtDNIActionPerformed);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        txtNombres.addActionListener(this::txtNombresActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnCrear)
                                        .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addComponent(txtNombres)
                                        .addComponent(txtDNI))
                                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(364, 364, 364))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addComponent(btnCrear)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear", jPanel2);

        cmbUsuarios.addActionListener(this::cmbUsuariosActionPerformed);

        cmbModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Nombres", "Apellidos", "Usuario", "Contraseña", "Rol" }));
        cmbModificar.addItemListener(this::cmbModificarItemStateChanged);

        lblNuevoDato.setText("Nuevo DNI:");

        jLabel7.setText("Usuario");

        jLabel8.setText("Modificar");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        lblActual.setText("DNI actual:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuevoDato)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(lblActual))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar)
                    .addComponent(cmbUsuarios, 0, 140, Short.MAX_VALUE)
                    .addComponent(cmbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModificar)
                    .addComponent(lblDato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addComponent(lblConsejo)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActual)
                    .addComponent(lblDato))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoDato)
                    .addComponent(txtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsejo))
                .addGap(26, 26, 26)
                .addComponent(btnModificar)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar", jPanel3);

        cmbUsuarios1.addActionListener(this::cmbUsuarios1ActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        jLabel9.setText("Elija un usuario para eliminar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cmbUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminar)))
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(cmbUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel1);

        jMenu1.setText("Cerrar sesión");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String dni = txtDNI.getText();
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        String usuario = txtUsuario.getText();
        String contraseña = txtContraseña.getText();
        String rol = cmbRol.getSelectedItem().toString();

        Usuario nuevo = null;

        if (rol.equals("Administrador")) {
            nuevo = new Administrador(dni, nombres, apellidos, usuario, contraseña);
        } else if (rol.equals("Supervisor")) {
            nuevo = new Supervisor(dni, nombres, apellidos, usuario, contraseña);
        } else if (rol.equals("Operador")) {
            nuevo = new Operador(dni, nombres, apellidos, usuario, contraseña);
        }

        if (nuevo != null) {
            sistema.registrarUsuario(nuevo);

            JOptionPane.showMessageDialog(null, "Usuario creado correctamente.");

            txtDNI.setText("");
            txtNombres.setText("");
            txtApellidos.setText("");
            txtUsuario.setText("");
            txtContraseña.setText("");
            cmbRol.setSelectedIndex(0);

            llenarComboBoxUsuarios();
            llenarComboBoxEliminar();
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolActionPerformed

    private void cmbUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuarios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUsuarios1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (cmbUsuarios1.getSelectedItem() != null) {
            if (cmbUsuarios1.getSelectedItem().toString().equalsIgnoreCase(usuarioLogueado.getUsername())) {
                JOptionPane.showMessageDialog(this, "No te puedes eliminar a ti mismo -__-", "Acción denegada", JOptionPane.WARNING_MESSAGE);
                return;
            }
            sistema.eliminarUsuario(cmbUsuarios1.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this, "Usuario '" + cmbUsuarios1.getSelectedItem().toString() + "' eliminado con éxito.");
            llenarComboBoxEliminar();
            llenarComboBoxUsuarios();
        } else {
            JOptionPane.showMessageDialog(this, "No hay ningún usuario seleccionado para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        VentanaLogin login = new VentanaLogin(sistema);
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MenuSelected

    private void cmbModificarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbModificarItemStateChanged
        if (cmbUsuarios.getSelectedItem() == null || cmbModificar.getSelectedItem() == null) {
            return;
        }
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String aspectoSeleccionado = cmbModificar.getSelectedItem().toString();
            String usuarioSeleccionado = cmbUsuarios.getSelectedItem().toString();

            Usuario u = sistema.buscarUsuarioPorUsername(usuarioSeleccionado);

            if (aspectoSeleccionado.equals("DNI")) {
                lblActual.setText("DNI actual:");
                lblDato.setText(u.getDni());
                lblNuevoDato.setText("Nuevo DNI:");
                lblConsejo.setText("");
            } else if (aspectoSeleccionado.equals("Nombres")) {
                lblActual.setText("Nombres actuales:");
                lblDato.setText(u.getNombres());
                lblNuevoDato.setText("Nuevos Nombres:");
                lblConsejo.setText("");
            } else if (aspectoSeleccionado.equals("Apellidos")) {
                lblActual.setText("Apellidos actuales:");
                lblDato.setText(u.getApellidos());
                lblNuevoDato.setText("Nuevos Apellidos:");
                lblConsejo.setText("");
            } else if (aspectoSeleccionado.equals("Usuario")) {
                lblActual.setText("Usuario actual:");
                lblDato.setText(u.getUsername());
                lblNuevoDato.setText("Nuevo Usuario:");
                lblConsejo.setText("");
            } else if (aspectoSeleccionado.equals("Contraseña")) {
                lblActual.setText("Contraseña actual:");
                lblDato.setText(u.getPassword());
                lblNuevoDato.setText("Nueva Contraseña:");
                lblConsejo.setText("");
            } else if (aspectoSeleccionado.equals("Rol")) {
                lblActual.setText("Rol actual:");
                lblDato.setText(u.getRol());
                lblNuevoDato.setText("Nuevo Rol:");
                lblConsejo.setText("Roles disponibles: Administrador, Supervisor, Operador");
            } else {
                lblNuevoDato.setText("Nuevo Dato:");
                lblConsejo.setText("");
            }
        }
    }//GEN-LAST:event_cmbModificarItemStateChanged

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (cmbUsuarios.getSelectedItem() != null && !txtModificar.getText().trim().isEmpty()) {
            String usuarioAModificar = cmbUsuarios.getSelectedItem().toString();
            String aspectoAElegir = cmbModificar.getSelectedItem().toString();
            String nuevoDato = txtModificar.getText().trim();

            boolean exito = sistema.modificarUsuario(usuarioAModificar, aspectoAElegir, nuevoDato);

            if (exito) {
                JOptionPane.showMessageDialog(this, "¡Usuario actualizado con éxito!");
                txtModificar.setText("");
                llenarComboBoxUsuarios();
                llenarComboBoxEliminar();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo realizar la modificación.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un usuario e ingresa el nuevo valor.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnModificarActionPerformed
    }

    private void cmbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuariosActionPerformed
        // TODO add your handling code here:
        if (cmbUsuarios.getSelectedItem() == null || cmbModificar.getSelectedItem() == null) {
            return;
        }
        cmbModificarItemStateChanged(new java.awt.event.ItemEvent(cmbModificar, 0, cmbModificar.getSelectedItem(), java.awt.event.ItemEvent.SELECTED));
    }//GEN-LAST:event_cmbUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbModificar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JComboBox<String> cmbUsuarios1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblActual;
    private javax.swing.JLabel lblConsejo;
    private javax.swing.JLabel lblDato;
    private javax.swing.JLabel lblNuevoDato;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtModificar;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
