package interfaz;

import drones.*;
import javax.swing.JOptionPane;
import usuarios.*;

public class VentanaOperador extends javax.swing.JFrame {

    private javax.swing.JFrame ventanaLogin;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaOperador.class.getName());
    private SistemaGestionDrones sistema;

    /**
     * Creates new form VentanaOperador
     */
    public VentanaOperador(SistemaGestionDrones sistema, javax.swing.JFrame ventanaLogin) {
        this.sistema = sistema;
        this.ventanaLogin = ventanaLogin;
        initComponents();

        cargarDronesValidos();
        cargarSedes();
        cargarMisionesActivas();
        cargarMisionesEnProceso();
        cmbTipoMision.addItem("Seleccione un dron primero...");
        setLocationRelativeTo(null);
    }

    public VentanaOperador() {
        initComponents();
    }

    private void cargarDronesValidos() {
        cmbDronesDisponibles.removeAllItems();
        cmbDronesDisponibles.addItem("Seleccione...");

        Dron[] lista = sistema.getDrones();
        int total = sistema.getContDrones();

        for (int i = 0; i < total; i++) {
            if (lista[i] != null) {
                if (lista[i].getEstado().equalsIgnoreCase("Disponible") && lista[i].getNivelBateria() >= 30) {
                    cmbDronesDisponibles.addItem(lista[i].getCodigo());
                }
            }
        }
    }

    private void cargarSedes() {
        cmbSedes.removeAllItems();
        cmbSedes.addItem("Seleccione...");

        Sede[] lista = sistema.getSedes();
        int total = sistema.getContSedes();

        for (int i = 0; i < total; i++) {
            if (lista[i] != null) {
                cmbSedes.addItem(lista[i].getCodigo());
            }
        }
    }

    private void actualizarTiposMisionPorDron(String codigoDron) {
        cmbTipoMision.removeAllItems();
        cmbTipoMision.addItem("Seleccione...");

        if (codigoDron == null || codigoDron.equals("Seleccione...")) {
            return;
        }

        Dron dron = sistema.buscarDronPorCodigo(codigoDron);

        if (dron instanceof DronVigilancia) {
            cmbTipoMision.addItem("Monitoreo de accesos");
            cmbTipoMision.addItem("Vigilancia aérea");

        } else if (dron instanceof DronEntrega) {
            cmbTipoMision.addItem("Entrega de suministros");

        } else if (dron instanceof DronTransmision) {
            cmbTipoMision.addItem("Transmisión de imágenes");
        }
    }

    private void cargarMisionesActivas() {
        cmbMisionesActivas.removeAllItems();
        cmbMisionesActivas.addItem("Seleccione...");

        Mision[] lista = sistema.getMisiones();
        int total = sistema.getContMisiones();

        for (int i = 0; i < total; i++) {
            if (lista[i] != null) {
                if (lista[i].getEstado().equalsIgnoreCase("En proceso") || lista[i].getEstado().equalsIgnoreCase("Pendiente")) {
                    cmbMisionesActivas.addItem(lista[i].getCodigo());
                }
            }
        }
    }

    private void cargarMisionesEnProceso() {
        cmbMisionesEnProceso.removeAllItems();
        cmbMisionesEnProceso.addItem("Seleccione...");

        Mision[] lista = sistema.getMisiones();
        int total = sistema.getContMisiones();

        for (int i = 0; i < total; i++) {
            if (lista[i] != null && lista[i].getEstado().equalsIgnoreCase("En proceso")) {
                cmbMisionesEnProceso.addItem(lista[i].getCodigo());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnCrearMision = new javax.swing.JButton();
        txtCodigoMision = new javax.swing.JTextField();
        txtFechaMision = new javax.swing.JTextField();
        txtHoraMision = new javax.swing.JTextField();
        cmbDronesDisponibles = new javax.swing.JComboBox<>();
        cmbSedes = new javax.swing.JComboBox<>();
        cmbTipoMision = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbMisionesActivas = new javax.swing.JComboBox<>();
        txtCodigoRuta = new javax.swing.JTextField();
        txtZonaAsignada = new javax.swing.JTextField();
        txtDuracionRuta = new javax.swing.JTextField();
        cmbPrioridadRuta = new javax.swing.JComboBox<>();
        btnRegistrarRuta = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmbMisionesEnProceso = new javax.swing.JComboBox<>();
        cmbEstadoPostVuelo = new javax.swing.JComboBox<>();
        txtDetallesMision = new javax.swing.JTextArea();
        btnFinalizarMision = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnReporteMisiones = new javax.swing.JButton();
        btnReporteDrones = new javax.swing.JButton();
        txtConsolaReportes = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(this::jTabbedPane1StateChanged);

        btnCrearMision.setText("Crear Misión");
        btnCrearMision.addActionListener(this::btnCrearMisionActionPerformed);

        cmbDronesDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDronesDisponibles.addActionListener(this::cmbDronesDisponiblesActionPerformed);

        cmbSedes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbTipoMision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Codigo de Misión");

        jLabel2.setText("Fecha de Misión");

        jLabel3.setText("Hora de Misión");

        jLabel4.setText("Drones Disponibles");

        jLabel5.setText("Sedes");

        jLabel6.setText("Tipo de Misión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btnCrearMision))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFechaMision, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(247, 247, 247)
                                .addComponent(txtCodigoMision, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbDronesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoraMision, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbSedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTipoMision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoMision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaMision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoraMision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDronesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoMision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(btnCrearMision)
                .addGap(52, 52, 52))
        );

        jTabbedPane1.addTab("Crear Misión", jPanel1);

        cmbMisionesActivas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPrioridadRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Alta", "2 - Media", "3 - Baja" }));

        btnRegistrarRuta.setText("Registrar Ruta");
        btnRegistrarRuta.addActionListener(this::btnRegistrarRutaActionPerformed);

        jLabel7.setText("Misiones Activas");

        jLabel8.setText("Codigo de Ruta");

        jLabel9.setText("Zona Asignada");

        jLabel10.setText("Duración en minutos");

        jLabel11.setText("Prioridad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbPrioridadRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmbMisionesActivas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigoRuta, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addComponent(txtZonaAsignada)
                        .addComponent(txtDuracionRuta)))
                .addGap(168, 168, 168))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(btnRegistrarRuta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMisionesActivas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZonaAsignada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuracionRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPrioridadRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(33, 33, 33)
                .addComponent(btnRegistrarRuta)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Ruta", jPanel2);

        cmbMisionesEnProceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMisionesEnProceso.addActionListener(this::cmbMisionesEnProcesoActionPerformed);

        cmbEstadoPostVuelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "En mantenimiento", "Batería baja" }));

        txtDetallesMision.setEditable(false);
        txtDetallesMision.setColumns(20);
        txtDetallesMision.setRows(5);

        btnFinalizarMision.setText("Finalizar Misión");
        btnFinalizarMision.addActionListener(this::btnFinalizarMisionActionPerformed);

        jLabel12.setText("Misión");

        jLabel13.setText("Nuevo Estado del Dron");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMisionesEnProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstadoPostVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnFinalizarMision))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(txtDetallesMision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMisionesEnProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstadoPostVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(txtDetallesMision, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnFinalizarMision)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Control de Misión", jPanel3);

        btnReporteMisiones.setText("Misiones por Sede");
        btnReporteMisiones.addActionListener(this::btnReporteMisionesActionPerformed);

        btnReporteDrones.setText("Estado Actual de Drones");
        btnReporteDrones.addActionListener(this::btnReporteDronesActionPerformed);

        txtConsolaReportes.setEditable(false);
        txtConsolaReportes.setColumns(20);
        txtConsolaReportes.setRows(5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(btnReporteMisiones))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(btnReporteDrones)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtConsolaReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnReporteMisiones)
                .addGap(18, 18, 18)
                .addComponent(btnReporteDrones)
                .addGap(18, 18, 18)
                .addComponent(txtConsolaReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reportes", jPanel4);

        jMenu1.setText("Cerrar Sesión");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenu1.addActionListener(this::jMenu1ActionPerformed);
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMisionActionPerformed
        String codigo = txtCodigoMision.getText().trim();
        String fecha = txtFechaMision.getText().trim();
        String hora = txtHoraMision.getText().trim();
        Object dronSel = cmbDronesDisponibles.getSelectedItem();
        Object sedeSel = cmbSedes.getSelectedItem();
        Object tipoSel = cmbTipoMision.getSelectedItem();

        if (codigo.isEmpty() || fecha.isEmpty() || hora.isEmpty()
                || dronSel == null || dronSel.toString().equals("Seleccione...")
                || sedeSel == null || sedeSel.toString().equals("Seleccione...")
                || tipoSel == null || tipoSel.toString().equals("Seleccione...")) {

            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos para crear la misión.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Dron dron = sistema.buscarDronPorCodigo(dronSel.toString());
        Sede sede = sistema.buscarSedePorCodigo(sedeSel.toString());

        if (dron == null || sede == null) {
            JOptionPane.showMessageDialog(this, "Error de consistencia: No se encontró el dron o la sede en el sistema.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Mision nuevaMision = new Mision(codigo, fecha, hora, tipoSel.toString(), "En proceso", sede, dron);

        boolean exito = sistema.crearMision(nuevaMision);

        if (exito) {
            JOptionPane.showMessageDialog(this, "¡Misión '" + codigo + "' creada con éxito!\nEl dron cambió su estado a 'En misión'.");
            cargarMisionesActivas();

            txtCodigoMision.setText("");
            txtFechaMision.setText("");
            txtHoraMision.setText("");
            cmbTipoMision.setSelectedIndex(0);

            cargarDronesValidos();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo crear la misión.\nVerifique que el dron esté disponible y mantenga un nivel de batería >= 30%.", "Restricción de Negocio", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearMisionActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        if (this.ventanaLogin != null) {
            this.ventanaLogin.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_jMenu1MenuSelected

    private void cmbDronesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDronesDisponiblesActionPerformed
        Object seleccionado = cmbDronesDisponibles.getSelectedItem();
        if (seleccionado != null) {
            actualizarTiposMisionPorDron(seleccionado.toString());
        }
    }//GEN-LAST:event_cmbDronesDisponiblesActionPerformed

    private void btnRegistrarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRutaActionPerformed
        Object misionSel = cmbMisionesActivas.getSelectedItem();
        String codigoRuta = txtCodigoRuta.getText().trim();
        String zona = txtZonaAsignada.getText().trim();
        String duracionStr = txtDuracionRuta.getText().trim();
        Object prioridadSel = cmbPrioridadRuta.getSelectedItem();

        if (misionSel == null || misionSel.toString().equals("Seleccione...")
                || codigoRuta.isEmpty() || zona.isEmpty() || duracionStr.isEmpty()
                || prioridadSel == null || prioridadSel.toString().equals("Seleccione...")) {

            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos de la ruta.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int duracion = 0;
        try {
            duracion = Integer.parseInt(duracionStr);
            if (duracion <= 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La duración debe ser un número entero mayor a 0.", "Dato inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int prioridad = Integer.parseInt(prioridadSel.toString().substring(0, 1));

        Mision misionDestino = sistema.buscarMisionPorCodigo(misionSel.toString());

        if (misionDestino == null) {
            JOptionPane.showMessageDialog(this, "No se encontró la misión seleccionada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        RutaVuelo nuevaRuta = new RutaVuelo(codigoRuta, zona, duracion, prioridad);

        if (misionDestino.getContRutas() < 10) {
            misionDestino.agregarRuta(nuevaRuta);
            JOptionPane.showMessageDialog(this, "¡Ruta '" + codigoRuta + "' agregada con éxito a la misión " + misionSel.toString() + "!");

            // Limpieza de casillas
            txtCodigoRuta.setText("");
            txtZonaAsignada.setText("");
            txtDuracionRuta.setText("");
            cmbPrioridadRuta.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, "Esta misión ya alcanzó el límite máximo de 10 rutas de vuelo.", "Arreglo Lleno xd", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarRutaActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (jTabbedPane1.getSelectedIndex() == 1) {
            cargarMisionesActivas();
            cargarMisionesEnProceso();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void cmbMisionesEnProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMisionesEnProcesoActionPerformed
        Object seleccionado = cmbMisionesEnProceso.getSelectedItem();
        if (seleccionado == null || seleccionado.toString().equals("Seleccione...")) {
            txtDetallesMision.setText("");
            return;
        }

        Mision m = sistema.buscarMisionPorCodigo(seleccionado.toString());
        if (m != null) {
            String detalles = "CÓDIGO DE MISIÓN: " + m.getCodigo() + "\n"
                    + "Tipo: " + m.getTipoMision() + "\n"
                    + "Sede Asignada: " + m.getSedeAsignada().getNombre() + "\n"
                    + "Dron Asignado: " + m.getDronAsignado().getCodigo() + " (" + m.getDronAsignado().getModelo() + ")\n"
                    + "Rutas registradas: " + m.getContRutas() + " tramos de vuelo.";
            txtDetallesMision.setText(detalles);
        }
    }//GEN-LAST:event_cmbMisionesEnProcesoActionPerformed

    private void btnFinalizarMisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarMisionActionPerformed
        Object misionSel = cmbMisionesEnProceso.getSelectedItem();
        Object estadoSel = cmbEstadoPostVuelo.getSelectedItem();

        if (misionSel == null || misionSel.toString().equals("Seleccione...")
                || estadoSel == null || estadoSel.toString().equals("Seleccione...")) {

            JOptionPane.showMessageDialog(this, "Por favor, seleccione una misión y el estado final del dron.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String codigoMision = misionSel.toString();
        String nuevoEstadoDron = estadoSel.toString();

        boolean exito = sistema.finalizarMision(codigoMision, nuevoEstadoDron);

        if (exito) {
            JOptionPane.showMessageDialog(this, "¡Misión " + codigoMision + " finalizada con éxito!\nEl dron ahora está en estado: " + nuevoEstadoDron);

            txtDetallesMision.setText("");
            cmbEstadoPostVuelo.setSelectedIndex(0);

            cargarMisionesEnProceso();
            cargarDronesValidos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al intentar finalizar la misión.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFinalizarMisionActionPerformed

    private void btnReporteMisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteMisionesActionPerformed
        Reportable reporteador = this.sistema;
        txtConsolaReportes.setText(reporteador.generarReporte());
    }//GEN-LAST:event_btnReporteMisionesActionPerformed

    private void btnReporteDronesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteDronesActionPerformed
        txtConsolaReportes.setText(sistema.generarReporteEstadoDrones());
    }//GEN-LAST:event_btnReporteDronesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaOperador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearMision;
    private javax.swing.JButton btnFinalizarMision;
    private javax.swing.JButton btnRegistrarRuta;
    private javax.swing.JButton btnReporteDrones;
    private javax.swing.JButton btnReporteMisiones;
    private javax.swing.JComboBox<String> cmbDronesDisponibles;
    private javax.swing.JComboBox<String> cmbEstadoPostVuelo;
    private javax.swing.JComboBox<String> cmbMisionesActivas;
    private javax.swing.JComboBox<String> cmbMisionesEnProceso;
    private javax.swing.JComboBox<String> cmbPrioridadRuta;
    private javax.swing.JComboBox<String> cmbSedes;
    private javax.swing.JComboBox<String> cmbTipoMision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCodigoMision;
    private javax.swing.JTextField txtCodigoRuta;
    private javax.swing.JTextArea txtConsolaReportes;
    private javax.swing.JTextArea txtDetallesMision;
    private javax.swing.JTextField txtDuracionRuta;
    private javax.swing.JTextField txtFechaMision;
    private javax.swing.JTextField txtHoraMision;
    private javax.swing.JTextField txtZonaAsignada;
    // End of variables declaration//GEN-END:variables
}
